version: "3"

services:
  stream-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: stream-server:latest
    container_name: stream-server
    ports:
      - 8554:8554
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 1935:1935
      - 8888:8888
      - 8889:8889
      - 8189:8189
      - 8890:8890
    restart: always
